server:
  port: 9292

spring:
  application:
    name: bankaccount-service
  data:
    mongodb:
      database: BankAccountdb
      host: mongo
      port: 27017
  cloud:
    config:
      uri: 
      - http://config-server:9196 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-eureka:8761/eureka/       
  
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health
  endpoint:
    health:
      show-details: always
      
resilience4j:
  circuitbreaker:
    instances:
      movementService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  timelimiter:
    configs:
      default:
        timeout-duration: 2000
        cancel-running-future: true
    instances:
      timelimiterSlow:
         baseConfig: default