server:
  port: 9294

spring:
  application:
    name: movement-service
  data:
    mongodb:
      database: Movementdb
      host: mongo
      port: 27017


  cloud:
    config:
      uri:
      - http://config-server:9196

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-eureka:8761/eureka/        

  


