eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
  
  
microservice:
  movement-service:
    endpoints:
      endpoint1:
        uri: http://MOVEMENT-SERVICE/movement/{id}
      endpoint2:
        uri: http://MOVEMENT-SERVICE/movement
  customer-service:
    endpoints:
      endpoint1:
        uri: http://CUSTOMER-SERVICE/customer/personal/{dni}
      endpoint2:
        uri: http://CUSTOMER-SERVICE/customer/personal
      endpoint3:
        uri: http://CUSTOMER-SERVICE/customer/business
